#!/usr/bin/env python3
"""Regenerate tools/_iq_tables.py from the installed gguf-py (ground truth).

Run:  python tools/_gen_iq_tables.py  (in the p311 env with `gguf` installed)
Output: tools/_iq_tables.py -- embedded lookup tables for the IQ quant family
(IQ2_XXS/IQ2_XS/IQ2_S/IQ3_XXS/IQ3_S/IQ1_S/IQ1_M) and IQ4_NL/IQ4_XS kvalues.

The tables originate in llama.cpp (ggml-quants.c); gguf-py copies them. We
extract from gguf-py so the exporter and the reference stay byte-identical.
"""
import re
from pathlib import Path

import gguf.quants as q

OUT = Path(__file__).resolve().parent / "_iq_tables.py"

CLASSES = ["IQ2_XXS", "IQ2_XS", "IQ2_S", "IQ3_XXS", "IQ3_S", "IQ1_S", "IQ1_M"]


def attr(cls, name):
    v = getattr(cls, name)
    return v


def fmt_bytes(b: bytes) -> str:
    # tokenize into escapes (\xNN) and printable chars, wrap on token boundaries
    tokens = []
    for byte in b:
        if 32 <= byte < 127 and byte not in (34, 92):
            tokens.append(chr(byte))
        else:
            tokens.append(f"\\x{byte:02x}")
    lines = []
    cur = ""
    for t in tokens:
        if cur and len(cur) + len(t) > 64:
            lines.append('    b"' + cur + '"')
            cur = ""
        cur += t
    if cur:
        lines.append('    b"' + cur + '"')
    return "\n".join(lines)


parts = []
parts.append('"""Generated by _gen_iq_tables.py — DO NOT EDIT BY HAND.')
parts.append("Lookup tables for the IQ quant family (from llama.cpp / gguf-py).")
parts.append('"""')
parts.append("")
parts.append("# IQ2_XXS sign table (128 bytes, from ggml-quants.c iq2xxs_init)")
parts.append("KSIGNS = (")
parts.append(fmt_bytes(q.IQ2_XXS.ksigns))
parts.append(")")
parts.append("")

for name in CLASSES:
    cls = getattr(q, name)
    parts.append(f"# {name}: grid {cls.grid_shape} map {cls.grid_map}")
    parts.append(f"{name}_GRID_SHAPE = {cls.grid_shape}")
    parts.append(f"{name}_GRID_MAP = {cls.grid_map}")
    parts.append(f"{name}_GRID_HEX = (")
    parts.append(fmt_bytes(cls.grid_hex))
    parts.append(")")
    if hasattr(cls, "delta"):
        parts.append(f"{name}_DELTA = np_placeholder")
    parts.append("")

parts.append("# IQ4_NL / IQ4_XS kvalues")
parts.append(f"IQ4_NL_KVALUES = {q.IQ4_NL.kvalues}")
parts.append(f"MXFP4_KVALUES = {q.MXFP4.kvalues}")
parts.append(f"NVFP4_KVALUES = {q.NVFP4.kvalues}")
parts.append("")

src = "\n".join(parts)
src = src.replace("np_placeholder", f"{float(q.IQ1_S.delta)}")  # delta value
OUT.write_text(src)
print(f"wrote {OUT} ({len(src)} bytes)")
